name = "cyrus-ai-notes"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "cyrus-ai-news"
database_id = "28633ce2-8efe-438d-9d0e-22eb6493eb98"
